### ISSUE TITLE
我部署成功了，但是gitlab合并和提交代码push这个接口失败了

### ISSUE THREAD

**Issue by techtqmall** [goodideal/gitlab-bot#1]
我部署成功了，但是gitlab合并和提交代码push这个接口失败了

**Comment by techtqmall** [comment]
Response body:
{"error":"webhook url error, webhookUrl: undefined"}

**Comment by goodideal** [comment]
这是因为启动的时候没有增加`WEBHOOK_URL_xxx`环境变量导致的
