### ISSUE TITLE
评论事件无法正确发送

### ISSUE THREAD

**Issue by xiaokLinux** [goodideal/gitlab-bot#5]
comment event：
![image](https://user-images.githubusercontent.com/19778317/112971739-1a6c1900-9182-11eb-8a5b-62718059b10f.png)

发出的消息体中没有message字段：
![image](https://user-images.githubusercontent.com/19778317/112971858-37a0e780-9182-11eb-8752-cbb81f047154.png)

**Comment by AngelBo** [comment]
怎么用pm2运行呀

**Comment by goodideal** [comment]
晚些修复

**Comment by goodideal** [comment]
v2.0已经支持

**Comment by goodideal** [comment]
> 怎么用pm2运行呀

没有必要使用pm2，用docker更方便
